### PR TITLE
[BUGFIX] Avoid segmentation faults when processing entities

### PR DESCRIPTION
**Pull request by ohader**
Related: #52

### CODE REVIEW

**Comment by ohader** [comment]
```
vendor/bin/phpunit --no-coverage --filter=/doctypeAndEntityAreRemoved/
PHPUnit 6.5.14 by Sebastian Bergmann and contributors.

[1]    63007 segmentation fault  vendor/bin/phpunit --no-coverage --filter=/doctypeAndEntityAreRemoved/
```

**Comment by lolli42** [comment]
+1 Confirmed the patch, this fixes the php segfaults we're experiencing.

**Review by lolli42 — APPROVED** [review]

**Review by andreasfernandez — APPROVED** [review]

**Review by lolli42 — APPROVED** [review]

**Comment by lolli42** [comment]
Hope it is ok to ping here. :)

This issue is kinda important to us since TYPO3 added svg-sanitizer as dependency to increase security. Those segfaults are nasty and of course an issue for our application stability.
The patch looks good to me and the added tests nail the specific issue.

Is there anything left we may have missed and we could help with to get this fixed and released?

Thanks for all the work on this project. Keep rocking :)

**Review by darylldoyle — APPROVED** [review]
Looks good to me! Thanks for the work, apologies for not merging this sooner

**Pull request merged**
