### PR TITLE
Allow the enable-background attribute

### PR DESCRIPTION
**Pull request by Bersman**
PR for #63

### CODE REVIEW

**Comment by xerc** [comment]
deprecated ; https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/enable-background

**Comment by ohader** [comment]
> deprecated ; https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/enable-background

Sure, but still being used in the wild. It's similar to `xlink:href` which still is used even it is deprecated (https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href).

**Review by ohader — APPROVED** [review]

**Comment by brianteeman** [comment]
Please merge this

**Comment by darylldoyle** [comment]
The `enable-background` attribute [has been deprecated](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/enable-background) from the SVG specification for some time. It only seems to be included in Illustrator exports now for some legacy reason. If it's not being actively used in the SVG (which I assume it's not) then I see no problem removing it.  As such I'd rather not add support for it. If support is needed for the attribute, I suggest extending the `AllowedAttributes` class and using the `setAllowedAttrs` method on the sanitiser to pass them in prior to running it.

**Pull request closed without merging**
