### PR TITLE
Added filterUnits to allowed attributes

### LINKED ISSUE #40: Add filterUnits to allowed attributes
We’ve run into an issue with SVGs exported from [Figma](https://www.figma.com/) that utilise the [`filterUnits`](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/filterUnits) attribute.

```svg
<filter ... filterUnits="userSpaceOnUse">
```

Are we able to include this in the attributes whitelist, or is there a reason for it’s exclusion?

### PR DESCRIPTION
**Pull request by joshuabaker**
Fixes #40

### CODE REVIEW

**Review by ohader — APPROVED** [review]

**Comment by geldmacher** [comment]
Is there an ETA for merging this?

**Comment by joshuabaker** [comment]
@darylldoyle Please can you merge this. 😊

**Comment by geldmacher** [comment]
If anyone is looking for a TYPO3 Hotfix until this is merged: https://gist.github.com/geldmacher/b7fc62df2e46834b2a35ee2634f9b2b7

**Comment by CiotkaCierpienia** [comment]
@darylldoyle Please merge this :)

@geldmacher Thank you so much for this example

**Review by darylldoyle — APPROVED** [review]
Thanks for this

**Pull request merged**
